version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dyn
permissions:
  - object: /home/ubuntu/dyn
    owner: ubuntu
    group: ubuntu
    mode: 4755
hooks:
  ApplicationStart:
   - location: ./scripts/start_server.sh
     timeout: 100
     runas: ubuntu 
  ApplicationStop:
   - location: ./scripts/stop_server.sh
     timeout: 30
     runas: ubuntu 
  ValidateService:
   - location: ./scripts/validate_server.sh
     timeout: 100
     runas: ubuntu
