version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dyn
permissions:
  - object: /home/ubuntu/dyn
    owner: ubuntu
    group: ubuntu
    mode: 4755
hooks:
  AfterInstall:
   - location: ./scripts/after_install.sh
     timeout: 30
     runas: root
  ApplicationStart:
   - location: ./scripts/start_server.sh
     timeout: 300
     runas: ubuntu 
  ApplicationStop:
   - location: ./scripts/stop_server.sh
     timeout: 30
     runas: ubuntu 
